### ISSUE TITLE
Feature request: add Power On/Off and Install Position command

### ISSUE THREAD

**Issue by andreaimpact** [bitfocus/companion-module-panasonic-ptz#1]
It would be useful to have the following commands.
- Power ON 
- Power  OFF
- Switch to Desktop  Install Position 
- Switch to Hanging  Install Position

**Comment by JeffreyDavidsz** [comment]
Power on/off is in the latest build now, could you test it?

**Comment by andreaimpact** [comment]
Hi Jeffrey,

I downloaded the latest win64 version companion-2.0.0-b6fc4d5-1883-win64 but I don’t see any ON/OFF action? Am I missing something?

Thank you

Andrea

Da: Jeffrey Davidsz <notifications@github.com>
Inviato: domenica 24 novembre 2019 14:08
A: bitfocus/companion-module-panasonic-ptz <companion-module-panasonic-ptz@noreply.github.com>
Cc: Andrea Tacchetti <andrea@impact.it>; Author <author@noreply.github.com>
Oggetto: Re: [bitfocus/companion-module-panasonic-ptz] Feature request: add Power On/Off and Install Position command (#1)


Power on/off is in the latest build now, could you test it?

**Comment by JeffreyDavidsz** [comment]
It seems the build server is full, so no updates from 18-11 are stored there. When cleaned download the latest, then it's there

**Comment by andreaimpact** [comment]
Yes, after writing you I noticed that the latest buld on repository is dated 18.11 and therefore that the module was not updated yet.

Thank you anyway

Andrea

Da: Jeffrey Davidsz <notifications@github.com>
Inviato: mercoledì 27 novembre 2019 12:34
A: bitfocus/companion-module-panasonic-ptz <companion-module-panasonic-ptz@noreply.github.com>
Cc: Andrea Tacchetti <andrea@impact.it>; Author <author@noreply.github.com>
Oggetto: Re: [bitfocus/companion-module-panasonic-ptz] Feature request: add Power On/Off and Install Position command (#1)


It seems the build server is full, so no updates from 18-11 are stored there. When cleaned download the latest, then it's there

**Comment by andreaimpact** [comment]
I confirm that Power On/Off is working. 
Still missing 
Switch to Desktop Install Position
Switch to Hanging Install Position

Thank you!

**Comment by McHauge** [comment]
Next module update will include the option to change the mode from desktop to hanging position, still need to test it though, hope to do so in the next weekend.

**Comment by McHauge** [comment]
This is now a part of the Beta builds, will close this for now, feel free to open it again if need's be

**Comment by airbenich** [comment]
Great! Thank you @McHauge Andreas!
