### ISSUE TITLE
TCP Control Port

### ISSUE THREAD

**Issue by daniep01** [bitfocus/companion-module-panasonic-ptz#17]
With multiple cameras the companion module requires different TCP port numbers for each camera. On my HE40 cameras I can only change the HTTP port, there doesn't appear to be a setting in the Panasonic GUI to change the TCP port. Does anyone know if/how this can be done?

**Comment by McHauge** [comment]
@daniep01 the TCP port is one you choose, it's one companion will ask the camera to use. So you will not find any settings for it on the camera itself

**Comment by daniep01** [comment]
Thanks for the explanation.
