### ISSUE TITLE
(Bug) Tally on Panasonic AE-150 Not Responding to VMix Program Variable

### ISSUE THREAD

**Issue by BrianMSimons** [bitfocus/companion-module-panasonic-ptz#18]
I grabbed the latest experimental build to play around with since the current stable one doesn't have my PTZ cameras or RP150 controller.  I wanted to use the variable "vmix:mix1_program" for each camera to trigger it's Tally Light and it doesn't work.  I was able to trigger the Tally lights from the RP-150 controller.

At one point I had Camera 1 Tally on from the RP-150 variable. I then changed it to the Vmix variable and the tally stayed on.  I cut to a different camera in Vmix and the Tally went off, as it should.  However it didn't light up the tally on the camera I cut to, and the tally on that camera didn't come back on when I cut back to it.

**Comment by McHauge** [comment]
I'll close this, as this is now fixed in the core, and should work as expected in all new beta releases
