### ISSUE TITLE
Autofocus off issue on Panasonic PTZ

### ISSUE THREAD

**Issue by DonSlotta** [bitfocus/companion-module-panasonic-ptz#20]
Hi there ,
I´m controlling Panasonic AW-UE70 and AW-HE130 PTZ cameras via Companion.
I´m able to turn the Autofocus on via the _**Focus Mode: Auto Focus**_.  But the command _**Focus Mode: Manual Focus**_ doesn´t turn it off. This happens on both camera types. Is this a bug?

**Comment by McHauge** [comment]
@DonSlotta first of all, what version of companion?
if you are on the beta, please try and enable debug to log and restart companion
then press the action and see what it reports in the log

**Comment by DonSlotta** [comment]
I´m using version v2.2.2(2.1.2-f4bcaf3-2679)

**Comment by McHauge** [comment]
please ty the Beta, the module has been rewritten with feedbacks and all

to download it click the "builds" button under the main download button: [link](https://bitfocus.io/companion/download/builds/)

**Comment by DonSlotta** [comment]
Thanks for for the link. I will try it. Do I need a specific build or just the latest? 
Sorry for these newbie questions.

**Comment by McHauge** [comment]
just the latest

another thing if you are on windows go to this folder %AppData%\Roaming\companion
and make a backup off all it's content. this is all your settings and buttons in companion, if something breaks, you can just download the release version again, and copy your backup back into this folder and you will be back to what you have now

**Comment by DonSlotta** [comment]
I tried version v2.2.0 (2.2.0-7cb0beb-2932).
Now both commands **Lens - Focus Mode: Auto Focus** and **Lens - Focus Mode: Manual Focus** turn the Autofocus mode on. None of them turn it off.

**Comment by McHauge** [comment]
would you mind enabling "debug to log" and restart companion
then press the action and see what it reports in the log
then post a screenshot of it

**Comment by DonSlotta** [comment]
I sent both commands for Auto Focus and Manual Focus. Both semm to send the same value. 

![IMG_20210227_200204.jpg](https://user-images.githubusercontent.com/79760202/109404483-d5787b00-7966-11eb-8cf3-9b719eaebe14.jpg)

**Comment by McHauge** [comment]
Thx I'll give it a look

**Comment by McHauge** [comment]
@BrianMSimons  just tested it, and it works fine here, please check your actions and verify that they are set correctly they should look like this (also added a picture of my log when testing): 

![image](https://user-images.githubusercontent.com/31018035/109404702-dad6c500-7968-11eb-8624-f602185e29d2.png)
![image](https://user-images.githubusercontent.com/31018035/109404688-b67ae880-7968-11eb-901d-81ec73a401a8.png)
![image](https://user-images.githubusercontent.com/31018035/109404693-c1ce1400-7968-11eb-90ee-19f37b74fe83.png)

**Comment by McHauge** [comment]
@DonSlotta   just tested it, and it works fine here, please check your actions and verify that they are set correctly they should look like this (also added a picture of my log when testing): 

![image](https://user-images.githubusercontent.com/31018035/109404702-dad6c500-7968-11eb-8624-f602185e29d2.png)
![image](https://user-images.githubusercontent.com/31018035/109404688-b67ae880-7968-11eb-901d-81ec73a401a8.png)
![image](https://user-images.githubusercontent.com/31018035/109404693-c1ce1400-7968-11eb-90ee-19f37b74fe83.png)

**Comment by DonSlotta** [comment]
I´ve double checked the action on my Auto Focus Off Button. It is the same action as in your test setup. See attached screenshot
Your action triggers the Send CMD: D10 command. Mine still the D11 like the Auto Focus On command. That´s weird.
![1614525592053](https://user-images.githubusercontent.com/79760202/109423762-0b5a4580-79e1-11eb-9e30-b22b8e02f945.jpg)

**Comment by McHauge** [comment]
Well, my bet then would be to make a backup of the setup, then try removing the instance an create new buttons, else try a completly clean setup and se if that helps

**Comment by DonSlotta** [comment]
I deleted the instances, created them new and made new buttons. Now it works. Except that the manual focus command triggers the Auto Focus on and the auto focus command turns it off. That's still weird but I totally can live with that. Thanks a lot for your support. It helped me a lot. Cheers.
