### ISSUE TITLE
i cant connect to aw-ue70 ptz cams, 

### ISSUE THREAD

**Issue by jwarnier-ibg** [bitfocus/companion-module-panasonic-ptz#23]
i have a lot of stuff in the network witch i can manage with companion, for the 6 ptz's i have enter the ip adresses, but the status dont go to green

do i have to use somewhere a login and / or password?

thx in advance

greetings Jan

**Comment by McHauge** [comment]
What version of Companion, this module had a complete re-write in the v2.2.0 betas

**Comment by McHauge** [comment]
That might solve your problem

**Comment by McHauge** [comment]
I'll close this as there has been no response from the issuer, @jwarnier-ibg feel free to open it up again if needs be.
