### ISSUE TITLE
Saving and recalling scene files

### ISSUE THREAD

**Issue by thomasdragsnes** [bitfocus/companion-module-panasonic-ptz#38]
Hi, we would love the functionality to save and recall scene files.

The use case for this is making color corrections to a specific lighting setup, but if an operator gets lost in the settings, i would like a quick way of recalling a safe standard preset that will be mostly right.

Is this possible to accomplish?

**Comment by spenjer1** [comment]
Was the scene change functionality able to be added directly into the module instead of needing to use a generic HTTP request module?

**Comment by josephdadams** [comment]
I don’t know. Another developer just said I could close it
