### ISSUE TITLE
AW-HE40

### ISSUE THREAD

**Issue by TBuTcher71** [bitfocus/companion-module-panasonic-ptz#42]
Tally used to just work... but after updates to Companion over the past year .. this easy feature has become unusable and not easy to get to work.
I can FORCE activate Tally on/off when pressing a button on the StreamDeck.
I can save/read the state of the tally..
However I can no longer simply have the tally light turn on the AW-HE40 Camera when the ATEM Mini Extreme: Tally: Program is activated.
Attached  are all the settings available.. Any direction on how to enable the Tally light on the camera when switched to Program or a fix would be appreciated.. As said it used to "just work"

![tempImageZkDRM9](https://user-images.githubusercontent.com/70005392/194683923-cd407975-f860-44d2-aa11-43c8da251d0d.gif)
![tempImagemMdTgb](https://user-images.githubusercontent.com/70005392/194683924-1e295478-7755-435f-a8c8-a1c12e5986ae.gif)
![tempImageDKMkkr](https://user-images.githubusercontent.com/70005392/194683926-90e26fb6-f341-4bc9-a812-06135bbfb0b9.gif)
![tempImageNEEPw7](https://user-images.githubusercontent.com/70005392/194683929-14157fe7-3118-409b-b491-6a2790b964e9.gif)
![tempImageBcNHXP](https://user-images.githubusercontent.com/70005392/194683940-3c27b8bb-70c1-4f10-9752-6b49ac819c3d.gif)

![tempImagezqPPPL](https://user-images.githubusercontent.com/70005392/194683915-52b119d5-354f-4689-adc2-db104245f07c.gif)

**Comment by cyprient** [comment]
Please check this issue #44, it may help you to recreate the previous tally behavior with Companion 3.0
