### ISSUE TITLE
[feature request] delete camera preset

### ISSUE THREAD

**Issue by chownchownchown** [bitfocus/companion-module-panasonic-ptz#70]
Hello,

sometimes we prepare our setup for a new customer. During this process, all presets must be deleted from the cameras. Is it possible to get a function for delete preset xy and/or delete all presets? Camera UE150

**Comment by cyprient** [comment]
Can you check this issue #31 and tell me if you want the same thing?

**Comment by cyprient** [comment]
I'll close this one. Do not hesitate to follow the updates of issue #31 😉
