### ISSUE TITLE
Error when selecting camera

### ISSUE THREAD

**Issue by Vesa-Stremia** [bitfocus/companion-module-panasonic-ptz#78]
When button press action is ptz-controller: Select camera I get the following error:

Instance/Wrapper/PTZ_Controller: Error executing action: Response unknown error

This doesn't hinder the function, I still get the camera selected on the controller, but my OCS kicks hard seeing the errors in Log. :')

-Companion version 3.2.0+6637-beta
-PTZ-controller = Panasonic AW-RP150

**Comment by premultiply** [comment]
This module is about controlling the PTZ cameras directly.
This is the wrong module repository for this issue.

Please have a look at the camera-controller module repository: https://github.com/bitfocus/companion-module-panasonic-camera-controller
