### ISSUE TITLE
Support for AW-UE150?

### ISSUE THREAD

**Issue by themediaguy1297** [bitfocus/companion-module-panasonic-ptz#9]
My church just bought 3 of these PTZ cameras was wondering if there is support for them on these modules?

P.S. Don't know if this was the right place to submit a question but this was the only place I could find.

--
Thanks,
Kody

**Comment by McHauge** [comment]
seems to works if you use the one for AW-UE70, at least I have used it like that all weekend :)

**Comment by McHauge** [comment]
After testing with the AW-UE150, I added it as supported, therefore I'm closing this for now.
